package com.picky.util;

import com.picky.core.GeneralException;

import java.io.*;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Properties;

public class IOUtil {

    public static InputStream getClassFile(Class<?> clazz) {
        String name = clazz.getName().replace('.', '/') + ".class";
        InputStream file = clazz.getClassLoader().getResourceAsStream(name);

        return file;
    }

    public static Collection<String> readLines(File file) {
        try {
            if (file.exists()) {
                BufferedReader reader = new BufferedReader(new FileReader(file));

                Collection<String> lines = new ArrayList<String>();

                String line = null;
                while((line = reader.readLine()) != null) {
                    lines.add(line);
                }

                return lines;
            }
            return null;
        } catch (Exception e) {
            throw new GeneralException(e);
        }
    }

    public static void writeLines(File file, Collection<String> lines, boolean append) {
        try {
            PrintWriter writer = new PrintWriter(new FileOutputStream(file, append), true);

            for (String line : lines) {
                writer.println(line);
            }
        } catch (Exception e) {
            throw new GeneralException(e);
        }
    }

    public static void writeProperties(File file, Properties props) {
        try {
            OutputStream out = new FileOutputStream( file );
            props.store(out, "# Generated by picky");
        } catch (Exception e) {
            throw new GeneralException(e);
        }

    }

}
